import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

import '../../features/patient/domain/entities/diagnosis_result.dart';
import '../../features/auth/domain/entities/user.dart';

class ReportService {
  Future<void> generateDiagnosisReport(
      DiagnosisResult diagnosis, User patient, User? doctor) async {
    final doc = pw.Document();
    
    // Load font if needed, otherwise use default
    // final font = await PdfGoogleFonts.interRegular();

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _buildHeader(),
              pw.Divider(),
              pw.SizedBox(height: 20),
              _buildPatientInfo(patient),
              pw.SizedBox(height: 20),
              _buildDiagnosisDetails(diagnosis, doctor),
              pw.SizedBox(height: 40),
              _buildFooter(),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => doc.save(),
      name: 'VitaGuard_Report_${diagnosis.id}.pdf',
    );
  }

  pw.Widget _buildHeader() {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('VitaGuard',
                style: pw.TextStyle(
                    fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue)),
            pw.Text('Smart Chest Disease Diagnosis',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
          ],
        ),
        pw.Text(DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now())),
      ],
    );
  }

  pw.Widget _buildPatientInfo(User patient) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(5)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Patient Information',
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 5),
          pw.Text('Name: ${patient.name}'),
          pw.Text('ID: ${patient.id}'),
          pw.Text('Email: ${patient.email}'),
        ],
      ),
    );
  }

  pw.Widget _buildDiagnosisDetails(DiagnosisResult diagnosis, User? doctor) {
    final color = diagnosis.diagnosis.toLowerCase().contains('pneumonia')
        ? PdfColors.red
        : PdfColors.green;

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('Diagnosis Result',
            style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 10),
        pw.Row(
          children: [
            pw.Text('Condition: ', style: const pw.TextStyle(fontSize: 14)),
            pw.Text(
              diagnosis.diagnosis,
              style: pw.TextStyle(
                  fontSize: 16, fontWeight: pw.FontWeight.bold, color: color),
            ),
          ],
        ),
        pw.SizedBox(height: 5),
        pw.Text('Confidence: ${(diagnosis.confidence * 100).toStringAsFixed(1)}%'),
        pw.Text('Date: ${DateFormat('yyyy-MM-dd HH:mm').format(diagnosis.timestamp)}'),
        
        if (diagnosis.doctorNotes != null) ...[
           pw.SizedBox(height: 20),
           pw.Text('Doctor Notes:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
           pw.Text(diagnosis.doctorNotes!),
        ],

        if (doctor != null) ...[
          pw.SizedBox(height: 20),
          pw.Divider(),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.end,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: [
                  pw.Text('Verified by:', style: const pw.TextStyle(fontSize: 10)),
                  pw.Text('Dr. ${doctor.name}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                ],
              ),
            ],
          ),
        ],
      ],
    );
  }

  pw.Widget _buildFooter() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Divider(),
        pw.SizedBox(height: 5),
        pw.Text(
          'This report is generated by AI and verified by medical professionals where indicated.',
          style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey),
        ),
        pw.Text(
          'VitaGuard © 2026',
          style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey),
        ),
      ],
    );
  }
}
